Repository SUMIO1/SUMIO, pull requests merged in 2024-05, with the labels that each got.

#1 [SIO-15] Github repo setup
  README.md
  README_dev.md
Labels: documentation, CI, technical

#6 [SIO-29] - Wczytanie i załadowanie zawartości CSV do aplikacji
  requirements.txt
  requirements_dev.txt
  src/example_package/csv_reader/config.py
  src/example_package/csv_reader/csv_reader.py
  src/example_package/csv_reader/sample.csv
Labels: enhancement

#5 [SIO-31] - Przygotowanie GUI
  requirements.txt
  src/example_package/gui/app.py
  src/example_package/gui/kivy/app.kv
Labels: enhancement, GUI

#10 Change csv data from age to date of birth"
  src/config/constraints.py
  src/resources/sample.csv
Labels: technical

#12 [SIO-fix] - Dodanie warunków na wiek i wagę w csv reader
  src/example_package/csv_reader/csv_reader.py
Labels: bug

#13 [SIO-89] - Widok profilu uczestnika
  src/example_package/gui/app.py
  src/example_package/gui/kivy/app.kv
  src/resources/icons/user_in_circle_48.png
Labels: frontend, GUI
